package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("My API", func() { // "My API" is the name of the API used in docs
	Title("Documentation title")      // Documentation title
	Description("The next big thing") // Longer documentation description
	Host("goa.design")                // Host used by Swagger and clients
	Scheme("https")                   // HTTP scheme used by Swagger and clients
	BasePath("/api")                  // Base path to all API endpoints
	Consumes("application/json")      // Media types supported by the API
	Produces("application/json")      // Media types generated by the API
})

var _ = Resource("Operands", func() { // Defines the Operands resource
	Action("add", func() { // Defines the add action
		Routing(GET("/add/:left/:right")) // The relative path to the add endpoint
		Description("add returns the sum of :left and :right in the response body")
		Params(func() { // Defines the request parameters
			// found in the URI (wildcards) and querystring
			Param("left", Integer, "Left operand") // Defines left parameter as path segment
			// captured by :left
			Param("right", Integer, "Right operand") // Define right parameter as path segment
			// captured by :right
		})
		Response(OK, "plain/text") // Defines response
	})
})
